apiVersion: v2
name: payment-service
description: Payment Status Microservice — AKS deployment chart
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Oluwaseun Vaughan
    email: pascalvaughan@gmail.com
keywords:
  - payment
  - fintech
  - microservice
